### ISSUE TITLE
Animated blocks

### ISSUE THREAD

**Issue by NordicGamerFE** [Focamacho/DupeFix-Project#100]
You can put animated blocks from the erebus in the mob duplicator from industral foregoing but probably works in some other mods also that duplicate mobs
-
You can also put the mimic crab from fish's undead rising in the mob duplicator

**Comment by focamacho** [comment]
I think it only happens when Exact Copy is on? This option is disable by default in Industrial Foregoing's config.
It is a feature from Industrial Foregoing, because the function is to make a exact copy of the entity.

You can disable Exact Copy in Industrial Foregoing's config. It also has a config for blacklisting entities if i'm not wrong.
