### ISSUE TITLE
Farlanders Mod + Soulbound = duplicate gear

### ISSUE THREAD

**Issue by Yourname942** [Focamacho/DupeFix-Project#8]
There is a mob from Farlanders called a Looter which normally steals your weapon from you until you kill it. However, if you have any variation of soulbound enchantment from several different mods, or if you anchor your gear via the spectre anchor from Random Things, the looter will still steal your weapon, but the soulbound/anchored gear prevents the loss of your gear, so it essentially just created a copy of your gear. (It will still drop your "stolen weapon" after you killed him)

**Comment by Focamacho** [comment]
I can't replicate this, are you sure the problem is Soulbound enchantment/Spectre anchor?
I made some tests with Soulbound from EnderIO & CoFH, and Spectre anchor from Random Things but no success trying to replicate the bug.
Can u test it with only any Soulbound enchantment mod & Farlanders mod installed?
